# .github/workflows/ci.yml

name: continuous-integration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "testthat"))'

      - name: Run tests
        run: |
          Rscript -e 'source("tests/test_helpers.R", local=FALSE, echo=FALSE)'
